-- Database: Simalend

-- DROP DATABASE IF EXISTS "Simalend";

CREATE DATABASE "Simalend"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Russian_Russia.1251'
    LC_CTYPE = 'Russian_Russia.1251'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

COMMENT ON DATABASE "Simalend"
    IS 'Database for project of simalend';

GRANT CONNECT ON DATABASE "Simalend" TO "Администратор";

GRANT ALL ON DATABASE "Simalend" TO postgres WITH GRANT OPTION;

GRANT CONNECT ON DATABASE "Simalend" TO "Блокировка";

GRANT CONNECT ON DATABASE "Simalend" TO "Только чтение";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE ALL ON TABLES FROM postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT SELECT ON TABLES TO "Только чтение";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLES TO "Администратор";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT SELECT ON SEQUENCES TO "Только чтение";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT USAGE ON SEQUENCES TO "Администратор";
ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT SELECT ON SEQUENCES TO "Администратор" WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT SELECT ON SEQUENCES TO "Блокировка";